CREATE DATABASE IF NOT EXISTS mj_website CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
USE mj_website;
CREATE TABLE IF NOT EXISTS users (id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT, name VARCHAR(80) NOT NULL, email VARCHAR(160) NOT NULL UNIQUE, password_hash VARCHAR(255) NOT NULL, created_at DATETIME NOT NULL, PRIMARY KEY(id)) ENGINE=InnoDB;
